#pragma once

#include "Event.h"

enum GameEventType
{
	EXIT = NUM_EVENT_TYPES,
	EXIT_APP_EVENT,
	MENU_SELECT_EVENT,
	PLAYER_MOVE_UP_EVENT,
	PLAYER_MOVE_DOWN_EVENT,
	PLAYER_MOVE_LEFT_EVENT,
	PLAYER_MOVE_RIGHT_EVENT,
	PLAYER_SHOOT_UP_EVENT,
	PLAYER_SHOOT_DOWN_EVENT,
	PLAYER_SHOOT_LEFT_EVENT,
	PLAYER_SHOOT_RIGHT_EVENT,
	PLAYER_SHOOT_UP_RIGHT_EVENT,
	PLAYER_SHOOT_UP_LEFT_EVENT,
	PLAYER_SHOOT_DOWN_RIGHT_EVENT,
	PLAYER_SHOOT_DOWN_LEFT_EVENT
};